### ISSUE TITLE
Generate yaml helper cannot generate all yaml

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#1173]
### Subject of the issue
While developing a feature, I have noted that the `_generate_yaml` method in `sceptre/cli/helpers.py` cannot handle all yaml.

### Your environment
* version of sceptre (sceptre --version): master
* version of python (python --version): 3.6.9
* which OS/distro: Ubuntu

### Steps to reproduce

Given this `stream`:

```python
{'DatalakeUser-iam-user-generic': {'StackResourceDrifts': [{'StackId': 'arn:aws:cloudformation:ap-southeast-2:111122223333:stack/DatalakeUser-iam-user-generic/77d13300-504f-11ec-987e-0a90a6c6d40e', 'LogicalResourceId': 'IAMUser', 'PhysicalResourceId': 'datalake_user', 'ResourceType': 'AWS::IAM::User', 'ExpectedProperties': '{"ManagedPolicyArns":["arn:aws:iam::aws:policy/AmazonAthenaFullAccess"],"Policies":[{"PolicyDocument":{"Statement":[{"Action":["lakeformation:SearchDatabasesByLFTags","glue:SearchTables","lakeformation:SearchTablesByLFTags","glue:GetPartitions","glue:GetDatabase","glue:GetTable","glue:GetTables","lakeformation:ListLFTags","lakeformation:GetResourceLFTags","lakeformation:GetLFTag","glue:GetDatabases","lakeformation:GetDataAccess"],"Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"},"PolicyName":"DatalakeUserBasic"}],"Tags":[{"Key":"Creator","Value":"sceptre"},{"Key":"Environment","Value":"personal1"},{"Key":"Version","Value":"1.0.0"},{"Key":"Project","Value":"DataLake"},{"Key":"Department","Value":"Me"},{"Key":"Team","Value":"DevOps"},{"Key":"Contact","Value":"me@personal1"}],"UserName":"datalake_user"}', 'ActualProperties': '{"ManagedPolicyArns":["arn:aws:iam::aws:policy/AmazonAthenaFullAccess"],"Policies":[{"PolicyDocument":{"Statement":[{"Action":["lakeformation:SearchDatabasesByLFTags","glue:SearchTables","lakeformation:SearchTablesByLFTags","glue:GetPartitions","glue:GetDatabase","glue:GetTable","glue:GetTables","lakeformation:ListLFTags","lakeformation:GetResourceLFTags","lakeformation:GetLFTag","glue:GetDatabases","lakeformation:GetDataAccess"],"Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"},"PolicyName":"DatalakeUserBasic"}],"Tags":[{"Key":"Creator","Value":"sceptre"},{"Key":"Environment","Value":"personal1"},{"Key":"Version","Value":"1.0.0"},{"Key":"Project","Value":"DataLake"},{"Key":"Department","Value":"Me"},{"Key":"Team","Value":"DevOps"},{"Key":"Contact","Value":"me@personal1"}],"UserName":"datalake_user"}', 'PropertyDifferences': [], 'StackResourceDriftStatus': 'IN_SYNC', 'Timestamp': datetime.datetime(2021, 11, 28, 14, 18, 46, 708000, tzinfo=tzutc())}], 'ResponseMetadata': {'RequestId': '7c6c1c0b-ffc1-4f92-a5fb-a57a6c1ec51a', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '7c6c1c0b-ffc1-4f92-a5fb-a57a6c1ec51a', 'content-type': 'text/xml', 'content-length': '3756', 'date': 'Sun, 28 Nov 2021 14:18:53 GMT'}, 'RetryAttempts': 0}}}
```

### Expected behaviour
The tool `cfn-flip` handles this fine and generates:

```yaml
DatalakeUser-iam-user-generic:
  StackResourceDrifts:
    - StackId: arn:aws:cloudformation:ap-southeast-2:111122223333:stack/DatalakeUser-iam-user-generic/77d13300-504f-11ec-987e-0a90a6c6d40e
      LogicalResourceId: IAMUser
      PhysicalResourceId: datalake_user
      ResourceType: AWS::IAM::User
      ExpectedProperties: >-
        {"ManagedPolicyArns":["arn:aws:iam::aws:policy/AmazonAthenaFullAccess"],"Policies":[{"PolicyDocument":{"Statement":[{"Action":["lakeformation:SearchDatabasesByLFTags","glue:SearchTables","lakeformation:SearchTablesByLFTags","glue:GetPartitions","glue:GetDatabase","glue:GetTable","glue:GetTables","lakeformation:ListLFTags","lakeformation:GetResourceLFTags","lakeformation:GetLFTag","glue:GetDatabases","lakeformation:GetDataAccess"],"Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"},"PolicyName":"DatalakeUserBasic"}],"Tags":[{"Key":"Creator","Value":"sceptre"},{"Key":"Environment","Value":"personal1"},{"Key":"Version","Value":"1.0.0"},{"Key":"Project","Value":"DataLake"},{"Key":"Department","Value":"Me"},{"Key":"Team","Value":"DevOps"},{"Key":"Contact","Value":"me@personal1"}],"UserName":"datalake_user"}
      ActualProperties: >-
        {"ManagedPolicyArns":["arn:aws:iam::aws:policy/AmazonAthenaFullAccess"],"Policies":[{"PolicyDocument":{"Statement":[{"Action":["lakeformation:SearchDatabasesByLFTags","glue:SearchTables","lakeformation:SearchTablesByLFTags","glue:GetPartitions","glue:GetDatabase","glue:GetTable","glue:GetTables","lakeformation:ListLFTags","lakeformation:GetResourceLFTags","lakeformation:GetLFTag","glue:GetDatabases","lakeformation:GetDataAccess"],"Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"},"PolicyName":"DatalakeUserBasic"}],"Tags":[{"Key":"Creator","Value":"sceptre"},{"Key":"Environment","Value":"personal1"},{"Key":"Version","Value":"1.0.0"},{"Key":"Project","Value":"DataLake"},{"Key":"Department","Value":"Me"},{"Key":"Team","Value":"DevOps"},{"Key":"Contact","Value":"me@personal1"}],"UserName":"datalake_user"}
      PropertyDifferences: []
      StackResourceDriftStatus: IN_SYNC
      Timestamp: '2021-11-28 14:15:53.795000+00:00'
  ResponseMetadata:
    RequestId: '0fe2ecc6-fc2a-43a1-8edd-b8024046a8aa'
    HTTPStatusCode: 200
    HTTPHeaders:
      x-amzn-requestid: '0fe2ecc6-fc2a-43a1-8edd-b8024046a8aa'
      content-type: text/xml
      content-length: '3756'
      date: Sun, 28 Nov 2021 14:16:01 GMT
    RetryAttempts: 0
```

### Actual behaviour

Because this `stream` is not a list, the code tries to `yaml.safe_loads` it, which raises `AttributeError("module 'yaml' has no attribute 'safe_loads'",)`. The method then returns the `stream` back to the caller.
