### ISSUE TITLE
'YAML not well-formed' error when having comments before the start of document line `---`

### ISSUE THREAD

**Issue by rubencabrera** [Sceptre/sceptre#1222]
### Subject of the issue

YAML files having comments above the start of document line (`---`) are not validated. 

### Your environment
* version of sceptre: 3.1.0
* version of python: 3.9.0
* which OS/distro: Tested on Ubuntu Focal and Alpine.

### Steps to reproduce
Running `sceptre validate` for any yaml template that has a comment before the start line. For example:

```
# This comment is valid!
---
AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket
Resources:
  S3ForIssue:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::Region}-s3bucketforissue"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```

Removing the comment from the first line passes validation. 

We have a few files with comments that worked with version `2.7.1` but all pipelines broke after we bumped to `3.1.0`.

### Expected behaviour

YAML files with comments before the document line pass validation. 

### Actual behaviour

Validation fails with:

```
"An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: YAML not well-formed. (line 3, column 1)"
```

I suppose how the error is displayed is a separate issue, but it's worth mentioning that debugging which file has the problem in a system where many templates are being passed to a CI validation job has been a chore.
