### ISSUE TITLE
Vars overwrite not working

### ISSUE THREAD

**Issue by teddevaal** [Sceptre/sceptre#1235]
### Subject of the issue
According to the [Variable Handling documentation](https://docs.sceptre-project.org/3.1.0/docs/cli.html#variable-handling), variables passed in with `--var` should overwrite variables defined in a var file. As documented below, this does not seem to be the behaviour when running it in my environment.

### Your environment
* version of sceptre (sceptre --version)
Sceptre, version 3.1.0
* version of python (python --version)
Python 3.9.12
* which OS/distro
macOs Big Sur Version 11.6.2 (20G314)

### Steps to reproduce
`config/config.yaml`
```
---
application:
  version: da84308
```
`config/master/create-resources.yaml`
```
---
template_path: master/create-resources-template.cfn.yaml

parameters:
  ApplicationVersion: "{{ application.version }}"
```

**Command:**
`sceptre --var application.version=2b80340 launch master/create-resources.yaml --yes`

### Expected behaviour
ApplicationVersion should be populated with `2b80340`

### Actual behaviour
ApplicationVersion is populated with `da84308`

**Comment by jfalkenstein** [comment]
Hi @teddevaal, I think you have misunderstood the documentation. `--var` doesn't override values on Stack Configs or StackGroup Configs. Rather, it overrides values in a var-file that you are _also_ specifying in the command. This is documented here: https://docs.sceptre-project.org/3.1.0/docs/cli.html#variable-handling

Thus, the correct approach would be this:

### config/config.yaml
```yaml
application:
    # All var references need to be accessed via var.xxxx
    version: {{ var.version }}  # This could also be {{ var.application.version }} but to make it clearer, I'm just using var.version
```

To be clear, that while you _can_ set this application key in config/config.yaml, you don't actually have to do that. The only benefit of setting keys like this in a StackGroup Config is that they will be "inherited" by all Stack Configs within that group unless otherwise overridden.

### config/master/create-resources.yaml
```yaml
# other stuff that is irrelevant to this issue

parameters:
    ApplicationVersion: {{ application.version }}  # This is referencing the StackGroup Config

### vars/production.yaml
 ```yaml
# This var-file would contain your main production variables. It doesn't need to be in a vars/ directory, but that's where 
# I like to put my own var-files, since I have var-files for dev, qa, staging, and prod
version: "abc123"
other_irrelevant_config: "hello"
```

### The command you would run
`sceptre --var-file vars/production.yaml --var version="override" launch config/master`

This would launch with the parameter version value populated as "override" rather than what the var-file says "abc123".

Anyway, I hope this helps. If you feel the documentation would be clearer, I'd be happy to review a PR from you to clarify the docs further so this doesn't get confused in the future.
