### ISSUE TITLE
embedded resolvers - resolver ouput as entry paramter for another resolver

### ISSUE THREAD

**Issue by tbensalem-bkom** [Sceptre/sceptre#1258]
### Subject of the issue
I have been trying to run embedded resolvers, to be exact I want to have a resolver output as input for another resolver.
I have described how I have implemented that below.
```
parameters:
   Param1: !CustomResolver1
      parameter1: !stack_output stack::output1
      parameter2: !stack_output stack::output2
```

### Your environment
* version of sceptre (3.1.0)
* version of python (3.9.1)
* which OS/distro (Windows)

### Expected behavior
I'm expecting the `!stack_output stack::output1` and `!stack_output stack::output2` to get resolved first than output it send to the upper-level function `!CustomResolver1`

### Actual behavior
it does not work
