### ISSUE TITLE
Attempt to launch stack with ContentUri fails to package local ref to content

### ISSUE THREAD

**Issue by thetumper** [Sceptre/sceptre#1290]
I'm attempting to create a lambda layer with a sceptre cloudformation template, with a local ref to the content.  This is failing when calling sceptre launch.

### Your environment
* version of sceptre (sceptre --version) --> 3.2.0
* version of python (python --version) --> 
* which OS/distro

### Steps to reproduce
The template looks like this.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My Application Content
Metadata:
  version: 1.0.0
Parameters:
  ApplicationName:
    Type: String
    Description: Application Name
    Default: myapp
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: dev
Resources:
  ContentLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x
      ContentUri: ../../../mycontent/
      Description: Layer containing additional content
      RetentionPolicy: Retain
  LayerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN for latest Content Layer
      Name: !Sub '/${ApplicationName}/${EnvironmentName}/content'
      Type: String
      Value: !Ref ContentLayer
```

### Expected behaviour
According to https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html, the ContentUri property is valid for a resource of type AWS::Serverless::LayerVersion, so it would be expected to operate by executing that packaging behavior, as part of the launch process.

### Actual behaviour
The sceptre launch command fails, with the error:

Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ContentLayerd315a6d0c4] is invalid. 'ContentUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.
