### ISSUE TITLE
Getting wrong template_path deprecation warning when deleting a stack

### ISSUE THREAD

**Issue by sp-albert-jubany** [Sceptre/sceptre#1335]
### Getting wrong template_path deprecation warning when deleting a stack
We use sceptre in an internal github repository. Our stacks use as a template Jinja2 files on the `templates` folder, so our stacks start like this:

```yaml
template:
  type: file
  path: role.j2
``` 

The stack is created succesfully, and we can update it without getting any warnings either. But when the stack is deleted, we get a deprecation warning saying that we are using the `template_path` key, but we are not (we use the template key instead).

```
sceptre delete config/lab/global/iam/role-test-axu.yaml
/Users/xxxxx/.pyenv/versions/3.10.11/envs/sceptre-4.1.0/lib/python3.10/site-packages/sceptre/stack.py:426: DeprecatedWarning: template_path is deprecated as of 4.0.0 and will be removed in 5.0.0. Use the template Stack Config key instead.
  setattr(self, deprecated_attribute_name, deprecated_value)
The following stacks, in the following order, will be deleted:
lab/global/iam/role-test-axu
```

### Your environment
* version of sceptre: 4.1.0
* version of python: 3.10.11
* which OS/distro: Mac, and also using official [docker image](https://hub.docker.com/r/sceptreorg/sceptre)

### Steps to reproduce
Delete a stack that is using as a template a local jinja2 file, like this:

```yaml
template:
  type: file
  path: role.j2
``` 

### Expected behaviour
The resource is deleted without raising a depreaction warning.

### Actual behaviour
A deprecation warning is raised, even if it's not using the deprecated key. The resource is deleted succesfully either way.

**Comment by jfalkenstein** [comment]
Hi @sp-albert-jubany Are you able to post your _entire_ StackConfig? I've looked through our codebase and there isn't a single reference to template_path that should have triggered that I can find. I'm wondering if you have any hooks or resolvers you're using that might be accessing `self.stack.template_path`.

**Comment by sp-albert-jubany** [comment]
Hello @jfalkenstein , sure no problem. It's just a test dummy role I created for this showcase on a laboratory account, but it happens to all of our stacks. As far as I know now hooks or resolvers are used for this kind of stack.

```yaml
template:
  type: file
  path: role.j2
sceptre_user_data:
  Name: role-test-axu
  Policies:
    - Name: cloudwatch
      Statements:
        - Action:
            - cloudwatch:DescribeAlarmsForMetric
            - cloudwatch:DescribeAlarmHistory
            - cloudwatch:DescribeAlarms
            - cloudwatch:ListMetrics
            - cloudwatch:GetInsightRuleReport
          Resource:
            - "*"
```
