### ISSUE TITLE
Stack outputs in stack groups hide the stack names

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#1356]
### An export format for stack outputs that shows stack name is needed
The main purpose of stack outputs is to consume them in other stacks. Example:

```yaml
VpcId: !stack_output network.yaml::VpcId
```

or in a var file:

```yaml
VpcId: '!stack_output_external my-network-stack::VpcId'
```

In the case of stack groups however, there is no easy way to know which stack exports which outputs without either reading the source, going to the AWS Console, or using AWS CLI commands. Furthermore, even knowing what the stack name of any stack is requires use of Sceptre's `list stacks` command as Sceptre's logic of setting the stack name has never been obvious.

The options we have are:

1. list outputs 
```
% sceptre --output=yaml list outputs
---                       
- direct-connect:                     
  - OutputKey: VPGWId     
    OutputValue: vgw-1fb1e1e1af11da11b
- vpc:                             
  - ExportName: nonprod-DataSubnetCIDRa
    OutputKey: DataSubnetCIDRa     
    OutputValue: 11.11.111.11/11      
  - ExportName: nonprod-PublicSubnetCIDRa
    OutputKey: PublicSubnetCIDRa      
    OutputValue: 11.11.111.111/11
...
```

This command is flawed, in that it does not report true stack names, but names like `direct-connect` and `vpc` that only have meaning inside Sceptre itself.

2. list outputs --export=envvar
```
% sceptre --output=yaml list outputs --export=envvar
export SCEPTRE_VPGWId='vgw-1fb1e1e1af11da11b'
export SCEPTRE_DataSubnetCIDRa='11.11.111.11/11'
export SCEPTRE_PublicSubnetCIDRa='11.11.111.111/11'
export SCEPTRE_DataSubnetCIDRb='11.11.111.11/11'
export SCEPTRE_VPCId='vpc-111111ab111a11e11'
...
```

This command is also flawed, as it does not report the stack name at all.

Note that this same CLI behaviour of listing outputs originates in the initial commit of this project back in 2017. In that original version of the code we had:

```python
@cli.command(name="describe-stack-outputs")
@stack_options
@click.option("--export", type=click.Choice(["envvar"]))
@click.pass_context
@catch_exceptions
def describe_stack_outputs(ctx, environment, stack, export):
    """
    Describes stack outputs.

    Describes ENVIRONMENT/STACK's stack outputs.
    """
    env = get_env(ctx.obj["sceptre_dir"], environment, ctx.obj["options"])
    response = env.stacks[stack].describe_outputs()

    if export == "envvar":
        write("\n".join(
            [
                "export SCEPTRE_{0}={1}".format(
                    output["OutputKey"], output["OutputValue"]
                )
                for output in response
            ]
        ))
    else:
        write(response, ctx.obj["output_format"])
```

### Proposal export=stackoutput and export=stackoutputexternal

In addition to `--export=envvar` options like `--export=stackoutput` and `--export=stackoutputexternal` are needed. They might look like this:

```
% sceptre list outputs --export=stackoutput
!stack_output direct-connect.yaml::VPGWId --- vgw-1fb1e1e1af11da111
!stack_output vpc.yaml::DataSubnetCIDRa --- 11.11.111.11/11
!stack_output vpc.yaml::PublicSubnetCIDRa --- 11.11.111.111/11
!stack_output vpc.yaml::DataSubnetCIDRb --- 11.11.111.11/11
!stack_output vpc.yaml::VPCId --- vpc-111111ab111a11e11
...
```
and

```
% sceptre list outputs --export=stackoutputexternal
!stack_output_external nonprod-direct-connect::VPGWId --- vgw-1fb1e1e1af11da111
!stack_output_external nonprod-vpc::DataSubnetCIDRa --- 11.11.111.11/11
!stack_output_external nonprod-vpc::PublicSubnetCIDRa --- 11.11.111.111/11
!stack_output_external nonprod-vpc::DataSubnetCIDRb --- 11.11.111.11/11
!stack_output_external nonprod-vpc::VPCId --- vpc-111111ab111a11e11
...
```
