### ISSUE TITLE
Provide a simple way to share config between stacks

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#256]
# Description of Enhancement 
There have been a number of similar requests to provide a simple and robust way to share configuration variables between stacks. A common pattern is to duplicate stack configs between environments, violating the DRY principle. This issue looks to amalgamate the slightly different discussions happening in other issues that touch on this topic. 

Issues that either request, suggest or mention similar functionality include:
- #64
- #154  
- #191 
- #253 

Any implementation should consider the proposed renaming of environments in #253, and also the effect of removing cascading configs as described in #64 (if that change goes ahead).

# Desired State
A single file that contains values of config that are used between stacks. The value of each config should be set against an environment (as defined in #253). The file could be structured as follows:

``` json
{ 
    "config-item": {
        "environment-1": "value-1",
        "environment-2": "value-2"
    } 
} 
```

As yaml:

```yaml
config-item:
    environment-1: value-1
    environment-2: value-2
```

Examples:
JSON
``` json
{ 
    "database_username": {
        "development": "dev-db-user",
        "test": "test-db-user",
        "production": "prod-db-user"
    } 
} 
```
YAML
```yaml
database_username:
    development: dev-db-user
    test: test-db-user
    production: prod-db-user
```

YAML would probably be the most appropriate format for the shared config file. 

For the stack configs in each environment, we could specify an ```environment``` key with the corresponding environment value. Or an alternative way to define which environment config to use would be to use directory name of the environment and throw an error if an unrecognised environment name was specified in the common stack config file. 

This work would require a handler to give the stack config access to the values stored in the common config file (if such functionality doesn't already exist within the project). 

# Scope of work
This issue should only implement the functionality to share common config across stacks. The implementation should be cognizant of the issues mentioned, but not dependent on them.

I welcome a discussion about any part of this proposal.

**Comment by theseanything** [comment]
My thoughts are having a top level key within config.yaml called something like `variables`. Under this key you can put any groups of variables you'd like to use. This would then replace "--var" and "--var-file" flags with something like "--vars"  to indicate with sub-key under `variables` to import and make available when templating stack configs. e.g.
```yaml
--- config/config.yaml ---
project_code: example_corp
region: eu-west-1
variables:
   dev:
        instance_size: t2.micro
        db_password: !environment_variable DEV_DB_PASSWORD
   prod:
        instance_size: x1.large
        db_password: !environment_variable PROD_DB_PASSWORD
```
```yaml
--- config/app1/backend.yaml ---
template_path: instances.py
parameters:
    InstanceSize: {{ var.instance_size }}
    DbPassword: {{ var.db_password }}
    DbUsername: "AdminUser"
```
`sceptre create app1/backend.yaml --vars dev`
