### ISSUE TITLE
Resolver of a parameter that is the output of another stack

### ISSUE THREAD

**Issue by sergioissi** [Sceptre/sceptre#379]
Hi, is it possible to give as input paramter to a resolver a parameter that is an output of another stack?
This is the example:
```
template_path: templates/roberto.yaml
parameters:
  Project: roberto
  Repository: !stack_output pipeline/ecr::Repository
  Tag: !get_tag !stack_output pipeline/ecr::Repository
```
This is the error:
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 3, column 3:
      Project: roberto
      ^
expected <block end>, but found '<tag>'
  in "<unicode string>", line 16, column 20:
      Tag: !get_tag !stack_output pipeline/ecr::Repository 

Trying like this:
```
template_path: templates/roberto.yaml
parameters:
  Project: roberto
  Repository: !stack_output pipeline/ecr::Repository
  Tag: !get_tag !Repository
```

This is the error:
Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''

**Comment by nabeelamjad** [comment]
You should be able to use `!stack_output_external`, let me know if something like this works:


```yaml
template_path: templates/roberto.yaml

parameters:
  ...
  Roberto: !stack_output_external pipeline/ecr::Repository
```
