### ISSUE TITLE
Reference stack_name from stack config

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#624]
I have a jinja template and would like to pass the stack_name to the template.  The only way to do this is to pass it in with a sceptre_user_data key.  Since it's already defined in each stack config it would be nice to be able to reference the stack_name instead of having to define multiple times.  This also applies to passing it to any plugin like hooks and parameters.

This works `template/test/noop.yaml`:
```
template_path: mystack.j2
stack_name: noop
sceptre_user_data:
  stackname: noop 
parameters:
  stackname: noop
hooks
  after_create:
    -  !cmd "python noop.py"  
```

However this would be much better `template/test/noop.yaml`
```
template_path: mystack.j2
stack_name: noop
sceptre_user_data:
  stackname: {{ stack_config.stack_name }} 
parameters:
  stackname: {{ stack_config.stack_name }}
hooks
  after_create:
    -  !cmd "python {{ stack_config.stack_name }}.py"  
```

**Comment by zaro0508** [comment]
related to issue #355

**Comment by zaro0508** [comment]
My workaround for this issue is to create the [sceptre-identity-resolver](https://github.com/zaro0508/sceptre-identity-resolver)

**Comment by zaro0508** [comment]
I didn't realize an important fact that all sceptre files are read in as jinja templates which means an even better workaround for this is to just use jinja

```
{% set StackName = "noop" %}
template_path: ec2.yaml
stack_name: {{ StackName }}
parameters:
  StackName: {{ StackName }}
sceptre_user_data:
  StackName: {{ StackName }}
hooks
  after_create:
    -  !cmd "python {{ StackName }}.py" 
```
