### ISSUE TITLE
Converting yaml to json

### ISSUE THREAD

**Issue by ryanpagel** [Sceptre/sceptre#639]
This is just a question... Is there a way to convert JSON to YAML as part of the template generation process?  I am writing AWS State Machine language as part of a stack and it has to be written in JSON but YAML would make it much easier to work with.  Here is an example...

![image](https://user-images.githubusercontent.com/805791/52895162-2e0fbd80-317c-11e9-9dda-837e9c268bce.png)

You can see the JSON that is assigned to the DefinitionString.  Thanks.

**Comment by 1oglop1** [comment]
can you share your `template` and `stack_config.yaml` file? 
It should be possible to write just yaml, we solved this by loading state `.json` file directly into a template written in troposphere.

**Comment by ryanpagel** [comment]
@1oglop1  We don't use troposphere for our templates.  We just use YAML templates with some Jinja2 (.j2 file extensions) for loops and conditions.  Our `stack_configs` are passing values through `sceptre_user_data`.   The screenshot in my above comment is part of one of our templates.  
I'm going to try what you you suggested and pass a yaml file in through the `sceptre_user_data`.  It looks like you're right, yaml gets converted into json, so this might work.

**Comment by ngfgrant** [comment]
You could use `sceptre --output yaml generate PATH/TO/STACK-OR-STACKGROUP` might get you most of the way there.

**Comment by ryanpagel** [comment]
I gave this a try and it work but has a couple limitations that are deal-breakers for us:

- the JSON it generates is not standard JSON that CloudFormation is happy with.  For example it replaces `null` values with the word "None" in double-quotes; it uses single-quotes for all JSON property names and values; it capitalizes the word `true` to `True`.  
- by passing the yaml-converted JSON string through `sceptre_user_data` we don't have a way to dynamically build the state machine based on varied inputs coming through `sceptre_user_data`.  For example, our `dev` environment may only have two parallel branches but `prod` may have four.  So we need a way to dynamically build the state machine rather than passing in a static value.

If there could be a way to convert the yaml to json after the template has been generated, that would probably be what I'm looking for.

**Comment by ryanpagel** [comment]
@ngfgrant I want to be able to define my AWS State Machine in YAML but have it converted to JSON when running `sceptre update`, etc.   Would that help me with that?

**Comment by ngfgrant** [comment]
Ok you might want to look into a custom `before_update` hook (https://sceptre.cloudreach.com/latest/docs/hooks.html) that uses a library to parse your yaml to json at runtime. Not sure this would 100% work but would be worth a shot.

**Comment by ryanpagel** [comment]
@ngfgrant  Thanks, I'll look into that.  Since I'm still on sceptre 1.x does the current hooks documentation still apply?

**Comment by ngfgrant** [comment]
Best to use the docs in the v1 branch in that case.

**Comment by 1oglop1** [comment]
@ryanpagel just in case here is a link https://github.com/cloudreach/sceptre/blob/v1/docs/docs/hooks.md
Or you could also try to write custom resolver
because resolver has access to the `stack_congfig`.

then you could process `stack_config.yaml` in similar way
```
def resolve(self)
        values = self.stack_config['state_machine_section'].get(self.argument)
        resolved_values = ResolvableProperty('resolver_name').resolve_values(values)
        return ''.join(resolved_values)
```

`secptre.ResolvableProperty` - will enable you to use other resolvers in STM definition
`resolved_values` - will contain python object (dict) which you can then return as `json.dumps(s)`

**Comment by ryanpagel** [comment]
@1oglop1 It appears that in sceptre 1.x we don't have access to the stack object from a custom hook.  We'll probably wait until we are able to upgrade to 2.x and take another look at that time.    In sceptre 2.x is it possible to actually change the content of the generated template before it is uploaded within a custom hook?

**Comment by 1oglop1** [comment]
The provided sample is exactly what am I using in `sceptre 1.4.2`.
the `self.stack_config` is only accessible inside `resolve()` method.
I will provide you a little broader example how do I imagine it could work

**Comment by 1oglop1** [comment]
@ryanpagel 

Here is a more complete example how I see it could work, it's not perfect but should do the job
https://gist.github.com/1oglop1/9aadac1a5185129a1891bc0bcf843757

I did not test it, but CFN should not have anything agains as `DefinitionString` is a string.

`recursive_get` function allows nested structure in `state_machines` definition in case you want to produce more than 1 within the `stack_config.yaml`
eg:
```
state_machines:
  orninary_sfns:
    sfn1: ... DefinitionString-yaml
    sfn2: ... DefinitionString-yaml
  special_sfn: ... DefinitionString-yaml
  extra_sfns:
    one_more_level:
      snf1: ... DefinitionString-yaml

template_path: state_machine.py
sceptre_user_data:
  ordinary_sfn1:
    StateMachineName: sfn1-name
    RoleArn: "arn:aws:iam::123456789012:role/role-name"
    DefinitionString: !state_machine_json orninary_sfns.sfn1
  ordinary_sfn2:
    StateMachineName: sfn2-name
    RoleArn: "arn:aws:iam::123456789012:role/role-name"
    DefinitionString: !state_machine_json orninary_sfns.sfn2
  special_sfn:
    StateMachineName: special_sfn-name
    RoleArn: "arn:aws:iam::123456789012:role/role-name"
    DefinitionString: !state_machine_json special_sfn
  extra_sfn:
    StateMachineName: extra_sfn1-name
    RoleArn: "arn:aws:iam::123456789012:role/role-name"
    DefinitionString: !state_machine_json extra_sfns.one_more_level.snf1
```
