### ISSUE TITLE
Jinja variables in yaml config files

### ISSUE THREAD

**Issue by aduzsardi** [Sceptre/sceptre#656]
It would be nice if we could use jinja variables in yaml files to avoid repetition

```yaml
sceptre_user_data:
    some_dict:
        whatever:  value

    another_dict:
        same_value: "{{ some_dict.whatever }}"  
```

by the way , does sceptre support yaml anchoring in config files ?

**Comment by zaro0508** [comment]
I believe yaml anchoring should be independent of sceptre.  sceptre uses pyaml to parse yaml so as long as pyaml library supports anchoring then it should be available.

In general, this request does seem like a useful feature.  In this use case I believe you can move some_dict to config yaml and reference it in the template yaml multiple times.

**Comment by aduzsardi** [comment]
yes i could, it's just that i would like to keep only global variables in config.yaml , it's not always the case, sometimes you have stack specific option that you keep reppeting

thanks for the input though , i actually went with a stackgroup config yaml for now :)

**Comment by iAnomaly** [comment]
Agreed with @aduzsardi that this would be useful for DRYing out repetitions.

Using the stack config file works as a workaround but it's less than ideal to store variables for a specific stack's concerns in the global config. You have to manage possible variable name collisions across stacks and remember to expand your find/replace search path when refactoring a specific stack.

**Comment by zaro0508** [comment]
There's probably a couple of different ways you can work around this issue.   One is using a stack group config file.  Another is to use use a resolver to load variables from ENV var or from config files.  Another option is to use yaml anchors which do work.  All parameters in `sceptre_user_data ` section are available to jinja templates.  Also you may be interested in related issue #760  


Yaml anchor Example:
```
template_path: test.yaml
stack_name: test-stack
stack-tags: &tags
  Department: "BioFreeze"
  Project: "Enzyme-Analysis"

parameters:
  <<: *tags
```
