### ISSUE TITLE
Would it be useful to access SceptreContext and stack_name in stack config?

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#760]
Hi all,

I am playing about with various things and looking to make some more information available in stack config. One thing which would be pretty easy to make available would be the SceptreContext (https://github.com/cloudreach/sceptre/blob/master/sceptre/context.py). 

It is then accessible like:

```yaml
...
stack_tags:
  context_item: {{context.project_path}}
```

I've also been able to easily add `stack_name` to the stack_config

accessible like:

```yaml
...
stack_tags:
  name: {{stack_name}}
```

Would this be useful?
