### ISSUE TITLE
Jinja Templating is Broken

### ISSUE THREAD

**Issue by chutes** [Sceptre/sceptre#857]
Jinja Templating appears to be broken...

A var file can be read in successfully as seen by the `Templating Vars:` output below.
Variable substitution is failing though as seen by the stacktrace....

```
$ sceptre  --var-file alpha.yaml launch load-balancer
Templating Vars from RENDER:
{'profile': 'alpha',
 'project_code': 'alpha',
 'project_path': 'H:\\src\\infrastructure\\aws',
 'region': 'us-east-1',
 'stack_group_config': {'profile': 'alpha',
                        'project_code': 'alpha',
                        'project_path': 'H:\\src\\infrastructure\\aws',
                        'region': 'us-east-1',
                        'stack_group_path': 'load-balancer'},
 'stack_group_path': 'load-balancer',
 'var': {'environment_name': 'Alpha',
         'load_balancer_rabbit_name': 'AlphRabbitLB'}}
Rendered Template
('\n'
 'template_path: load-balancer-network.py\n'
 '\n'
 'parameters:\n'
 '  ### Using !stack_output_external vs !stack_output.\n'
 '  ### Stack Output does not support custom stack names.\n'
 '  ### We have to use custom stack names currently because Windows '
 'namespacing\n'
 '  ### is not normalized in v2 of spectre as of yet.\n'
 '  VpcId: !stack_output_external alpha-vpc::VpcId\n'
 '  Subnets:\n'
 '  - !stack_output_external cornerstone-vpc::PrivateSubnet1\n'
 '  - !stack_output_external cornerstone-vpc::PrivateSubnet2\n'
 '\n'
 '#  ### FOR TESTING ONLY::: Rabbit is intentionally inside public subnets '
 'until we get a vpn setup\n'
 "#  LoadBalancerScheme: 'internet-facing'\n"
 '#  Subnets:\n'
 '#    - !stack_output_external cornerstone-vpc::PublicSubnet1\n'
 '#    - !stack_output_external cornerstone-vpc::PublicSubnet2\n'
 '\n'
 'sceptre_user_data:\n'
 '  load_balancer_name: {{ var.load_balancer_rabbit_name }}\n'
 '  is_private: "false"\n'
 '  tcp_ports:\n'
 "    'Rabbit Data': 5672\n"
 "    'Rabbit Management': 15672\n"
 '\n'
 '  ### Available target types: instance | ip | lambda\n'
 "  target_type: 'instance'\n"
 '  health_check:\n'
 '    interval_seconds: 30\n'
 '    timeout_seconds: 10\n'
 '    healthy_threshold_count: 4\n'
 '    unhealthy_threshold_count: 4\n'
 '\n'
 'dependencies:\n'
 '- vpc.yaml\n')
Traceback (most recent call last):
  File "c:\python36-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\src\venv-infra\Scripts\sceptre.exe\__main__.py", line 9, in <module>
  File "h:\src\venv-infra\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "h:\src\venv-infra\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "h:\src\venv-infra\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "h:\src\\venv-infra\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "h:\src\venv-infra\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "h:\src\venv-infra\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "h:\src\venv-infra\lib\site-packages\sceptre\cli\helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "h:\src\venv-infra\lib\site-packages\sceptre\cli\launch.py", line 35, in launch_command
    plan = SceptrePlan(context)
  File "h:\src\venv-infra\lib\site-packages\sceptre\plan\plan.py", line 34, in __init__
    all_stacks, command_stacks = config_reader.construct_stacks()
  File "h:\src\venv-infra\lib\site-packages\sceptre\config\reader.py", line 219, in construct_stacks
    stack = self._construct_stack(rel_path, stack_group_config)
  File "h:\src\venv-infra\lib\site-packages\sceptre\config\reader.py", line 454, in _construct_stack
    config = self.read(rel_path, stack_group_config)
  File "h:\src\venv-infra\lib\site-packages\sceptre\config\reader.py", line 272, in read
    this_config = self._recursive_read(directory_path, filename, config)
  File "h:\src\venv-infra\lib\site-packages\sceptre\config\reader.py", line 313, in _recursive_read
    child_config = self._render(directory_path, filename, stack_group_config) or {}
  File "h:\src\venv-infra\lib\site-packages\sceptre\config\reader.py", line 364, in _render
    config = yaml.safe_load(rendered_template)
  File "h:\src\venv-infra\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "h:\src\venv-infra\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "h:\src\\venv-infra\lib\site-packages\yaml\constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "h:\src\venv-infra\lib\site-packages\yaml\constructor.py", line 52, in construct_document
    for dummy in generator:
  File "h:\src\venv-infra\lib\site-packages\yaml\constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "h:\src\venv-infra\lib\site-packages\yaml\constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "h:\src\venv-infra\lib\site-packages\yaml\constructor.py", line 134, in construct_mapping
    "found unhashable key", key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 21, column 23:
      load_balancer_name: {{ var.load_balancer_rabbit_name }}
                          ^
found unhashable key
  in "<unicode string>", line 21, column 24:
      load_balancer_name: {{ var.load_balancer_rabbit_name }}
```

**Comment by ngfgrant** [comment]
Hi @chutes 

Thanks for raising. I've been unable to reproduce this error and none of the tests seem to have a problem running. 

Can you please check your config and var files are valid?

**Comment by chutes** [comment]
@ngfgrant AFAIK my config file and var files are valid.  You can see in the output I provided that the var-file is loaded in to `ConfigReader.templating_vars` excerted here... as

```
{'profile': 'alpha',
 'project_code': 'alpha',
 'project_path': 'H:\\src\\infrastructure\\aws',
 'region': 'us-east-1',
 'stack_group_config': {'profile': 'alpha',
                        'project_code': 'alpha',
                        'project_path': 'H:\\src\\infrastructure\\aws',
                        'region': 'us-east-1',
                        'stack_group_path': 'load-balancer'},
 'stack_group_path': 'load-balancer',
 'var': {'environment_name': 'Alpha',
         'load_balancer_rabbit_name': 'AlphRabbitLB'}}
```

I updated my config file to try to do a super simple jinja2 templating case....  this is my config with one var replacement....
If I remove the jinja templating, this launches just fine.

```
{% raw %}
template_path: load-balancer-network.py

parameters:
  VpcId: !stack_output_external vpc::VpcId
  Subnets:
  - !stack_output_external vpc::PrivateSubnet1
  - !stack_output_external vpc::PrivateSubnet2

sceptre_user_data:
  load_balancer_name: {{ var.load_balancer_rabbit_name }}
  is_private: "false"
  tcp_ports:
    'Rabbit Data': 5672
    'Rabbit Management': 15672

  ### Available target types: instance | ip | lambda
  target_type: 'instance'
  health_check:
    interval_seconds: 30
    timeout_seconds: 10
    healthy_threshold_count: 4
    unhealthy_threshold_count: 4

dependencies:
- vpc.yaml

{% endraw %}
```

**Comment by ngfgrant** [comment]
Hi thanks for the additional info. Could you give an example of the type of thing you are trying to do with jinja templates in your config?

**Comment by chutes** [comment]
I have a var-file with the variable `load_balancer_rabbit_name` defined.

I'm trying to do a simple variable replacement using jinja templating...
Replace `{{ var.load_balancer_rabbit_name }}` with the value I have defined...

However this error is throw....
```
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 21, column 23:
      load_balancer_name: {{ var.load_balancer_rabbit_name }}
                          ^
found unhashable key
  in "<unicode string>", line 21, column 24:
      load_balancer_name: {{ var.load_balancer_rabbit_name }}
```

It's almost as if the jinja templating is not recognized.

**Comment by ngfgrant** [comment]
can you share the full output from that config file because that type of jinja templating works ....

**Comment by chutes** [comment]
The full output is in the opening comment (with extra output that I have printed from the `ConfigReader`).
The command ran was `sceptre  --var-file alpha.yaml launch load-balancer`

**Comment by ngfgrant** [comment]
The output from the jinja engine after it has attempted to parse the file is what is in the first comment, can you just share what is in the the file directly?

**Comment by chutes** [comment]
which file are you referring to?  the `--var-file`?

This is the var-file.... `alpha.yaml`

```
environment_name: Alpha
load_balancer_rabbit_name: AlphaCornerstoneRabbitLB
```

**Comment by ngfgrant** [comment]
Apologies should have been clearer, the config for the stack `load-balancer` it should be under the `config/` directory?

**Comment by chutes** [comment]
This is the config for `load-balancer`

````
{% raw %}
template_path: load-balancer-network.py

parameters:
  VpcId: !stack_output_external vpc::VpcId
  Subnets:
  - !stack_output_external vpc::PrivateSubnet1
  - !stack_output_external vpc::PrivateSubnet2

sceptre_user_data:
  load_balancer_name: {{ var.load_balancer_rabbit_name }}
  is_private: "false"
  tcp_ports:
    'Rabbit Data': 5672
    'Rabbit Management': 15672

  ### Available target types: instance | ip | lambda
  target_type: 'instance'
  health_check:
    interval_seconds: 30
    timeout_seconds: 10
    healthy_threshold_count: 4
    unhealthy_threshold_count: 4

dependencies:
- vpc.yaml

{% endraw %}
```
