### ISSUE TITLE
generate command does not execute hooks

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#874]
I use the `!cmd` hook in my main and dependent sceptre files to download [shared templates](https://github.com/Sage-Bionetworks/itsandbox-infra/blob/master/config/prod/AccountAlertTopics.yaml#L14).  In my case the sceptre generate command fails because it does not run the hook to download the needed CFN template files for sceptre to process.  Is there a way to force the generate command to execute hooks?   Just a note that when I run the `launch` command the hooks are executed.

Here's a simple example:

in `templates/noop.yaml`
```
Description: noop template
AWSTemplateFormatVersion: 2010-09-09
Resources:
  touchNothing:
    Type: AWS::CloudFormation::WaitConditionHandle
```

in `config/prod/A.yaml`
```
template_path: "noop.yaml"
stack_name: "A"
hooks:
  before_create:
    - !cmd "echo test before_create for A"
  before_update:
    - !cmd "echo test before_update for A"
```

in `config/prod/main.yaml`
```
template_path: "noop.yaml"
stack_name: "main"
dependencies:
  - "prod/A.yaml"
hooks:
  before_create:
    - !cmd "echo test before_create for main"
  before_update:
    - !cmd "echo test before_update for main"
```

execute generate:
```
sceptre --debug --output yaml generate prod/main.yaml
```
*Note: the output does NOT contain `test before_create for A` and `test before_create for main` which means the hooks did not get executed.

execute launch:
```
sceptre --output yaml launch prod/main.yaml 
```
*Note: the hooks do get executed and the output does contain `test before_create for A` and `test before_create for main`
