### ISSUE TITLE
How to use `!stack_output` on  output.export.name?

### ISSUE THREAD

**Issue by schlichtanders** [Sceptre/sceptre#883]
Dear sceptre-team,

on the [cloudformation outputs documentation]( https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html)

the output export field is required to be globally unique. The official example itself recommends to prepend the StackName
```yaml
Export:
  Name: !Join [ ":", [ !Ref "AWS::StackName", AccountVPC ] ]
```
very similar is my own example, here as part of the Outputs section, which uses `-` instead of the `:` above
```yaml
Outputs:
  AccountVPC:
    ...
    Export:
      Name: !Sub '${AWS::StackName}-AccountVPC'
```

How would you refer to such a variable with sceptre's ``stack_output``Resolver?

I tried it with `!stack_output mystack::AccountVPC`, however I get an Error ``The Stack 'fullname-of-mystack' does not have an output named 'AccountVPC'``
