### ISSUE TITLE
Cannot set AWS Cognito Email/SMS templates using parameters

### ISSUE THREAD

**Issue by jacob-swanson** [Sceptre/sceptre#907]
I'm having an issue where part of my string parameter is getting erased by Sceptre.
The value in question is `{####}`, which is used by AWS Cognito as a template placeholder.
When this value is passed as a parameter in Sceptre, it's removed.

Config snippet:
```yaml
template_path: cognito/pool.yaml
parameters:
  ...
  InviteEmailTemplate: >
    Welcome, click this link to confirm your account:
    https://example.com/confirm?username={username}&confirmationCode={####}
```

Template snippet:
```yaml
Parameters:
  InviteEmailTemplate:
    Description: Template for user invite email.
    Type: String
...
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      ...
      AdminCreateUserConfig:
        InviteMessageTemplate:
          EmailMessage: !Ref InviteEmailTemplate
...
```

The value that is sent to CloudFormation is:
```
Welcome, click this link to confirm your account:
https://example.com/confirm?username={username}&confirmationCode=
```
Which fails due to it missing `{####}` with the following error:
```
 Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*\{####\}[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*
```
