### ISSUE TITLE
sceptre adding parentheses to formula causes failure

### ISSUE THREAD

**Issue by armanos** [Sceptre/sceptre#936]
In attempting to create an RDS Parameter Group, some of the values of the parameters are provided to AWS as formulas. It appears, based on the errors returned by AWS that Sceptre is adding parentheses to the cloudformation stack that is pushed up to AWS.

Example data:
```
template_path: param_group.yaml.j2
sceptre_user_data:
  instance_parameter_group:
    description: 'test RDS Aurora MySQL instance parameter group'
    family: 'aurora-mysql5.7'
    parameters:
      aurora_lab_mode: '0'
      binlog_cache_size: '32768'
      default_tmp_storage_engine: 'InnoDB'
      explicit_defaults_for_timestamp: '1'
      innodb_adaptive_hash_index: '0'
      innodb_buffer_pool_size: '"{DBInstanceClassMemory*3/4}"'
      innodb_flush_method: 'O_DIRECT'
      key_buffer_size: '16777216'
      local_infile: '1'
      log_output: 'FILE'
      max_connections: 'GREATEST({log(DBInstanceClassMemory/805306368)*45}, {log(DBInstanceClassMemory/8187281418)*1000})'
      performance_schema: '0'
      query_cache_size: '"{DBInstanceClassMemory/24}"'
      query_cache_type: '1'
      read_buffer_size: '262144'
      read_only: '"{TrueIfReplica}"'
      read_rnd_buffer_size: '524288'
      relay_log_info_repository: 'TABLE'
      sql_mode: '0'
      table_definition_cache: 'LEAST({DBInstanceClassMemory/393040}, 20000)'
      table_open_cache: 'LEAST({DBInstanceClassMemory/1179121}, 6000)'
      thread_stack: '262144'

```

Template (`param_group.yaml.j2`):
```
Resources:
  RDSInstanceParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: {{ sceptre_user_data.instance_parameter_group.description }}
      Family: {{ sceptre_user_data.instance_parameter_group.family }}
      Parameters:
        {% for instance_param in sceptre_user_data.instance_parameter_group.parameters -%}
        {{ instance_param }}: {{ sceptre_user_data.instance_parameter_group.parameters[instance_param] }}
        {% endfor %}

```

The error returned when creating this stack is: `RDSInstanceParameterGroup AWS::RDS::DBParameterGroup CREATE_FAILED The function syntax you have provided (GREATEST({log(DBInstanceClassMemory/805306368)*45}, {log(DBInstanceClassMemory/8187281418)*1000})) is invalid. The valid format is: GREATEST(argument1, argument2, ...) (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: [REDACTED]; Proxy: null)`

After testing a number of values, I can see that there is an additional set of parentheses around the value of the parameter that is passed to AWS, which clearly are not present in my vars file. This is not a valid, accepted format in AWS for this type of formula. I cannot see anywhere in `reader.py` that would be adding these, though.

**Comment by craighurley** [comment]
Are you intending for this:

`max_connections: 'GREATEST({log(DBInstanceClassMemory/805306368)*45}, {log(DBInstanceClassMemory/8187281418)*1000})'`

to be result in a CFN tempalate line that looks like this?

`max_connections: 'GREATEST(NUMBER1, NUMBER2)'`

If so, have you tried using double curly braces like this:

`max_connections: 'GREATEST({{log(DBInstanceClassMemory/805306368)*45}}, {{log(DBInstanceClassMemory/8187281418)*1000}})'`

**Comment by armanos** [comment]
Thanks for the speedy reply @craighurley - the CFN template should result in that formula as the value. If you search this [AWS doc](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html) for `DB Parameter Values` you will see that formulas are supported as values in DB parameter groups. This value in my yaml should be interpreted literally.

**Comment by armanos** [comment]
it took a while to sort out the simple function piece, also shown in the vars file above (e.g. `innodb_buffer_pool_size: '"{DBInstanceClassMemory*3/4}"'`) which required the 2 types of quotes in order to be interpreted in a way that played nicely with Sceptre/AWS, however I can confirm that this notation succeeds.

**Comment by armanos** [comment]
It appears that sceptre is generating/populating the template correctly and that this issue may be with CloudFormation/AWS.

```
%  sceptre generate test/pg.yaml
Resources:
  RDSInstanceParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: test RDS Aurora MySQL instance parameter group
      Family: aurora-mysql5.7
      Parameters:
        aurora_lab_mode: 0
        binlog_cache_size: 32768
        default_tmp_storage_engine: InnoDB
        explicit_defaults_for_timestamp: 1
        innodb_adaptive_hash_index: 0
        innodb_buffer_pool_size: "{DBInstanceClassMemory*3/4}"
        innodb_flush_method: O_DIRECT
        key_buffer_size: 16777216
        local_infile: 1
        log_output: FILE
        max_connections: "GREATEST({log(DBInstanceClassMemory/805306368)*45}, {log(DBInstanceClassMemory/8187281418)*1000})"
        performance_schema: 0
        query_cache_size: "{DBInstanceClassMemory/24}"
        query_cache_type: 1
        read_buffer_size: 262144
        read_only: "{TrueIfReplica}"
        read_rnd_buffer_size: 524288
        relay_log_info_repository: TABLE
        sql_mode: 0
        table_definition_cache: "LEAST({DBInstanceClassMemory/393040}, 20000)"
        table_open_cache: "LEAST({DBInstanceClassMemory/1179121}, 6000)"
        thread_stack: 262144
```

I have attempted to create the stack directly in the AWS console with this yaml and the result is the same (adds parentheses).
