### ISSUE TITLE
Support nested stacks

### ISSUE THREAD

**Issue by nikolay** [Sceptre/sceptre#95]

**Comment by theseanything** [comment]
Again similar to AWS:Include, I agree it may be handy for Sceptre to make sure nested templates are uploaded to S3 before.

**Comment by jamesroutley** [comment]
What's actually this issue here? I'm not super familiar with nested stacks.

**Comment by theseanything** [comment]
Just re-iterate the nested stacks are CloudFormation templates which have CloudFormation Stack resources. Those resources reference another CloudFormation within S3. So I guess to would be good to have Sceptre upload all the dependent templates to S3.

**Comment by Varriount** [comment]
How hard would it be to add this functionality to Sceptre? We use nested stacks quite a bit in our environments, and it would be a valuable feature to have.

**Comment by JuanCanham** [comment]
This is currently handled by `aws cloudformation deploy`, so it's implemented by https://github.com/cloudreach/sceptre/issues/324

I have a hook code to implement that, just going through internal review to decide if it should be in the sceptre repo or as a separate plugin. The issue with it, is that it depends on the awscli (the only place SAM is implemented, by AWS)

**Comment by zaro0508** [comment]
@JuanCanham would you be able to share your hook code for cloudformation deploy?

**Comment by aweiland** [comment]
> 
> 
> This is currently handled by `aws cloudformation deploy`, so it's implemented by #324
> 
> I have a hook code to implement that, just going through internal review to decide if it should be in the sceptre repo or as a separate plugin. The issue with it, is that it depends on the awscli (the only place SAM is implemented, by AWS)

Would you be able to share this?  I could use this today even if it's not in a final form.

**Comment by jk2l** [comment]
what is the current status of this?

**Comment by zaro0508** [comment]
I think the approach for resolving this is to update the current [sceptre template handlers](https://sceptre.cloudreach.com/dev/docs/template_handlers.html) to upload local templates to an S3 bucket so that AWS can resolve templates defined in [cloudformation nested stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html).  It might also be appropriate to create a custom template handler for this as well.

**Comment by avatarworf** [comment]
@zaro0508 is there an example how how to configure this, just a bit confused by the moving parts.  We can have a Cloudformation Stack managed by Sceptre create another Cloudformation file, but unsure how you'd related the template file

**Comment by jfalkenstein** [comment]
@avatarworf I think the basic idea is this:
1. Create a custom hook that runs `before_create` and `before_update` that takes a template name and uploads the template, probably to f`'s3://{self.stack.template_bucket_name}/{self.stack.template_key_prefix}/{self.stack.name}/{template_name}`.
2. Then you could pass that full path as a parameter to your template
3. Your template can use that parameter to create the nested stack.

That will work... but it's a bit clumsy. I think a better approach might be if someone created a template handler that would look something like:

```yaml
template:
    type: FileWithNestedStacks
    path: path/to/top/template.yaml.j2
    nested_template_bucket: !stack_attr template_bucket_name
    nested_templates:
        # The template handler will do a simple find/replace on the string of "my_first_nested_template" with the
        # full s3 path of the template uploaded. That way your template can just use "my_first_nested_template" as the 
        # template path instead of it being a full s3 path.
        my_first_nested_template: path/to/first/nested/template.yaml 
```

If you'd be interested in creating a PR for something like this, I'd be happy to work with you on that. 

Personally, I don't really like nested stacks. Sceptre seems to remove all the need for them (for my use cases, at least), since you can just have multiple stacks easily "wired together" instead of embedding stacks in other stacks.
